name: ComexGPT Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependências
        run: pip install -r requirements.txt
      - name: Executar bot
        run: python post_to_teams.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          CHAT_PROMPT: "Qual o status da última DI?"
